CREATE TABLE IF NOT EXISTS public.usuario (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre character varying(255) NOT NULL,
    email character varying(255) NOT NULL,
    edad integer NOT NULL,
    pokemon_ids character varying(255),
    CONSTRAINT uk_usuario_email UNIQUE (email)
);
