version: 2.1

orbs:
  coveralls: coveralls/coveralls@2.2.5
  
executors:
  java-executor:
    docker:
      - image: cimg/openjdk:17.0
    working_directory: ~/project/challange-ejercicio

jobs:
  build-and-test:
    executor: java-executor
    steps:
      - checkout:
          path: ~/project

      # Restaura dependencias almacenadas en caché para acelerar el build
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            - v1-dependencies-

      # Otorga permisos de ejecución al Maven Wrapper y descarga dependencias
      - run:
          name: Preparar entorno y dependencias
          command: |
            chmod +x mvnw
            ./mvnw dependency:go-offline

      # Guarda las dependencias en caché
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

      # Ejecuta las pruebas y genera el informe de cobertura de JaCoCo
      - run:
          name: Ejecutar Pruebas Automatizadas y Reporte JaCoCo
          command: |
            ./mvnw clean test jacoco:report

      # Almacena los resultados de los tests para verlos en la interfaz de CircleCI
      - store_test_results:
          path: target/surefire-reports

      # Reporte de cobertura para Coveralls pasando la variable de entorno
      - coveralls/upload:
          coverage_file: target/site/jacoco/jacoco.xml
          token: COVERALLS_REPO_TOKEN

workflows:
  pipeline-integracion-continua:
    jobs:
      - build-and-test