# Puerto de mi aplicaci\u00f3n Spring Boot
server.port=8080

# Conexi\u00f3n a la base de datos PostgreSQL en Docker
spring.datasource.url=jdbc:postgresql://localhost:5432/challange_db
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.default_schema=public

# Desactivar la generaci\u00f3n/modificaci\u00f3n autom\u00e1tica de tablas por Hibernate
spring.jpa.hibernate.ddl-auto=none

# Habilitar Flyway
spring.flyway.enabled=true
# Permite marcar la BD actual como versi\u00f3n inicial (Baseline)
spring.flyway.baseline-on-migrate=true
spring.flyway.baseline-version=1

# Habilita la opci\u00f3n de limpiar la BD local para pruebas/desarrollo
spring.flyway.clean-disabled=false

# Indicar el paquete o ubicaci\u00f3n del migration
spring.flyway.locations=classpath:db/migration

# Ajustes de inicializaci\u00f3n para evitar la dependencia circular con JPA
spring.sql.init.mode=never
spring.jpa.defer-datasource-initialization=false

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Configuraci\u00f3n Swagger / OpenAPI UI
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# Habilitar HTTPS condicionalmente (activado en local por defecto)
server.ssl.enabled=${SERVER_SSL_ENABLED:true}
server.ssl.key-store=classpath:keystore.p12
server.ssl.key-store-type=PKCS12
server.ssl.key-store-password=123456
server.ssl.key-alias=springboot

# ==========================================
# CONFIGURACI\u00d3N PARA MYSQL (Pr\u00e1ctica)
# ==========================================
#spring.datasource.url=jdbc:mysql://localhost:3306/challange_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
#spring.datasource.username=root
#spring.datasource.password=root
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate para MySQL
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true

# Configuraci\u00f3n Pok\u00e9API
pokeapi.base-url=https://pokeapi.co/api/v2
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.h2.H2ConsoleAutoConfiguration