#Puerto de mi aplicaci\u00f3n Spring Boot
server.port=8080

#Conexi\u00f3n a la base de datos PosgreSQL en Docker
spring.datasource.url=jdbc:postgresql://localhost:5432/challange_db
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

#Configuraci\u00f3n JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#Configuraci\u00f3n Swagger / OpenAPI UI
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html





# ==========================================
# CONFIGURACI\u00d3N PARA MYSQL (Pr\u00e1ctica)
# ==========================================
#spring.datasource.url=jdbc:mysql://localhost:3306/challange_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
#spring.datasource.username=root
#spring.datasource.password=root
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate para MySQL
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true

# Configuraci\u00f3n Pok\u00e9API
pokeapi.base-url=https://pokeapi.co/api/v2