-- 1. Limpieza previa de la tabla si ya existe
DROP TABLE IF EXISTS public.usuario CASCADE;

-- 2. Creación de la tabla 'usuario' según el modelo de tu entidad Spring Boot
CREATE TABLE public.usuario (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre character varying(255) NOT NULL,
    email character varying(255) NOT NULL,
    edad integer NOT NULL,
    pokemon_ids character varying(255),
    CONSTRAINT uk_usuario_email UNIQUE (email)
);

-- 3. Inserción de los datos guardados
INSERT INTO public.usuario (id, nombre, email, edad, pokemon_ids) OVERRIDING SYSTEM VALUE VALUES
(1, 'Ricardo', 'rdl@gmail.com', 30, '1,4,7'),
(2, 'Andrea', 'andrea@gmail.com', 28, '25,150'),
(3, 'Lidelma', 'lidelma@gmail.com', 35, '6,9'),
(4, 'Gabriel', 'gabriel@gmail.com', 25, '12,18'),
(5, 'Marcos', 'marcos@gmail.com', 29, '1,25'),
(6, 'Carmela', 'carmela@gmail.com', 27, '4,7'),
(7, 'Mariana', 'mariana@gmail.com', 31, '150,151'),
(8, 'Lucas', 'lucas@gmail.com', 24, '3,6'),
(9, 'Sofia', 'sofia@gmail.com', 26, '9,12'),
(10, 'Gonzalo', 'gonzalo@gmail.com', 33, '18,22'),
(11, 'Valeria', 'valeria@gmail.com', 32, '39,40'),
(12, 'Joaquin', 'joaquin@gmail.com', 22, '52,53'),
(13, 'Camila', 'camila@gmail.com', 28, '64,65'),
(14, 'Esteban', 'esteban@gmail.com', 34, '92,93');

-- 4. Actualización del contador de la secuencia para evitar conflictos en próximos INSERTs
SELECT setval(pg_get_serial_sequence('public.usuario', 'id'), (SELECT MAX(id) FROM public.usuario));