version: '3.8'

services:
  postgres-db:
    image: postgres:16-alpine
    container_name: challange
    restart: always
    environment:
      POSTGRES_DB: challange_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    external: true
    name: challange-ejercicio_postgres_data
